defmodule Shipstation.Structs.Order do
  @moduledoc ~s"""
  Parameters used when creating an order
  """
  alias Shipstation.Structs.{Address, OrderItem, Weight, Dimension,
                             InsuranceOption, InternationalOption,
                             AdvancedOption}

  @type t :: %Shipstation.Structs.Order{
    orderNumber: String.t,
    orderKey: String.t,
    orderDate: String.t,
    paymentDate: String.t,
    shipByDate: String.t,
    orderStatus: String.t,
    customerId: integer,
    customerUsername: String.t,
    customerEmail: String.t,
    billTo: Address.t,
    shipTo: Address.t,
    items: [OrderItem.t],
    amountPaid: float,
    taxAmount: float,
    shippingAmount: float,
    customerNotes: String.t,
    internalNotes: String.t,
    gift: boolean,
    giftMessage: String.t,
    paymentMethod: String.t,
    requestedShippingService: String.t,
    carrierCode: String.t,
    serviceCode: String.t,
    packageCode: String.t,
    confirmation: String.t,
    shipDate: String.t,
    weight: Weight.t,
    dimensions: Dimension.t,
    insuranceOptions: InsuranceOption.t,
    internationalOptions: InternationalOption.t,
    advancedOptions: AdvancedOption.t,
    tagIds: [integer],
    userId: String.t,
    externallyFulfilled: boolean,
    externallyFulfilledBy: String.t
  }

  defstruct orderNumber: nil,
    orderKey: nil,
    orderDate: nil,
    paymentDate: nil,
    shipByDate: nil,
    orderStatus: nil,
    customerId: nil,
    customerUsername: nil,
    customerEmail: nil,
    billTo: %Address{},
    shipTo: %Address{},
    items: [],
    amountPaid: 0,
    taxAmount: 0,
    shippingAmount: 0,
    customerNotes: nil,
    internalNotes: nil,
    gift: false,
    giftMessage: nil,
    paymentMethod: nil,
    requestedShippingService: nil,
    carrierCode: nil,
    serviceCode: nil,
    packageCode: nil,
    confirmation: nil,
    shipDate: nil,
    weight: %Weight{},
    dimensions: %Dimension{},
    insuranceOptions: %InsuranceOption{},
    internationalOptions: %InternationalOption{},
    advancedOptions: %AdvancedOption{},
    tagIds: [],
    userId: nil,
    externallyFulfilled: false,
    externallyFulfilledBy: nil
end
