defmodule Shipstation.Structs.Product do
  @moduledoc ~s"""
  This struct is used for describing products
  """
  alias Shipstation.Structs.{ProductCategory, ProductTag}

  @type t :: %Shipstation.Structs.Product{
    productId:               integer,
    sku:                     String.t,
    name:                    String.t,
    price:                   float,
    defaultCost:             float,
    length:                  float,
    width:                   float,
    height:                  float,
    weightOz:                float,
    internalNotes:           String.t,
    fulfillmentSku:          String.t,
    createDate:              String.t,
    modifyDate:              String.t,
    active:                  boolean,
    productCategory:         ProductCategory.t,
    productType:             String.t,
    warehouseLocation:       String.t,
    defaultCarrierCode:      String.t,
    defaultServiceCode:      String.t,
    defaultPackageCode:      String.t,
    defaultIntlCarrierCode:  String.t,
    defaultIntlPackageCode:  String.t,
    defaultConfirmation:     String.t,
    defaultIntlConfirmation: String.t,
    customsDescription:      String.t,
    customsValue:            String.t,
    customsTariffNo:         String.t,
    customsCountryCode:      String.t,
    noCustoms:               boolean,
    tags:                    ProductTag.t
  }

  defstruct productId:               0,
            sku:                     nil,
            name:                    nil,
            price:                   0.0,
            defaultCost:             0.0,
            length:                  0.0,
            width:                   0.0,
            height:                  0.0,
            weightOz:                0.0,
            internalNotes:           nil,
            fulfillmentSku:          nil,
            createDate:              nil,
            modifyDate:              nil,
            active:                  false,
            productCategory:         %ProductCategory{},
            productType:             nil,
            warehouseLocation:       nil,
            defaultCarrierCode:      nil,
            defaultServiceCode:      nil,
            defaultPackageCode:      nil,
            defaultIntlCarrierCode:  nil,
            defaultIntlPackageCode:  nil,
            defaultIntlServiceCode:  nil,
            defaultConfirmation:     nil,
            defaultIntlConfirmation: nil,
            customsDescription:      nil,
            customsValue:            nil,
            customsTariffNo:         nil,
            customsCountryCode:      nil,
            noCustoms:               false,
            tags:                    %ProductTag{}
end
